### ISSUE TITLE
Breaking change from #201 not noted as such in changelog

### ISSUE THREAD

**Issue by gsnedders** [w3c/webidl2.js#319] opened 2019-05-13 14:45 UTC
#201 breaks idlharness.js, because `extAttrs` is no longer an array.

**Comment by saschanaz** [comment] 2019-05-13 14:56
Right, but not sure how to fix this for github changelog generator...

BTW, I'd like to restore it as an array to remove the need of painful existence check. The problem is it needs array subclassing, do you think it's okay to do? I somehow am hesitant with no actual reason 🤔 @marcoscaceres

**Comment by gsnedders** [comment] 2019-05-13 15:11
Unsurprising, plenty of the trivia changes are breaking, and I keep finding more. Bleh. :/

`interface Foo : Bar` now has an object for `IdlInterface.base`, too, and array subclassing won't fix that.

**Comment by marcoscaceres** [comment] 2019-05-13 15:18
> BTW, I'd like to restore it as an array to remove the need of painful existence check. The problem is it needs array subclassing, do you think it's okay to do? I somehow am hesitant with no actual reason 🤔 @marcoscaceres

I don't have a strong opinion... if it lessens some pain for @gsnedders on the WPT side, then probably worth doing. 

@gsnedders, how bad are the breakages?

**Comment by gsnedders** [comment] 2019-05-13 15:22
@marcoscaceres They're all over the place, and without any static types I scarcely know how to find all the places where things have changed to be objects to include tokens etc., but as noted in my previous comment, there are things which have changed from `string` to an object, and that's a bigger change that can't be so easily be worked around.

**Comment by marcoscaceres** [comment] 2019-05-13 15:25
@gsnedders, sorry, one last bit of info: what's using WebIDL2.js on the WPT side? Is it IDLHarness?

**Comment by gsnedders** [comment] 2019-05-13 15:26
@marcoscaceres yes

**Comment by saschanaz** [comment] 2019-05-14 02:04
>plenty of the trivia changes are breaking

I recently reverted many of those string-to-object things. Might be easier to jump to the latest version...

**Comment by saschanaz** [comment] 2019-07-06 10:18
c8cca88a3fa6775b01900749c81e45a799113846 marked it as breaking change.

**Closed by saschanaz** 2019-07-06 10:18 UTC
